### ISSUE TITLE
Change context - to DP

### ISSUE THREAD

**Issue by anushkumar27** [lolster/LazyMap#2]
Sushi please change context of App.java, attached some of them here 
https://github.com/lolster/LazyMap/blob/dp-project/src/main/java/com/ansu/LazyMap/App.java#L42

**Comment by lolster** [comment]
Made changes necessary in [line 42](https://github.com/lolster/LazyMap/blob/dp-project/src/main/java/com/ansu/LazyMap/App.java#L42) and [line 69](https://github.com/lolster/LazyMap/blob/dp-project/src/main/java/com/ansu/LazyMap/App.java#L69).
